os:
  - linux

language:
  - cpp

services:
  - docker

compiler:
  - clang

addons:
  apt:
    packages:
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
  - sudo pip3 install meson

script:
  - meson build
  - ninja -C build test