version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: nychtelios/meson-build:0.3
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run: 
          name: Build
          command: meson build
      - run: 
          name: Run tests
          command: ninja -C build test

workflows:
  mqtt-system-monitor-workflow:
    jobs:
      - build:
          post-steps:
            - codecov/upload
