version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: nychtelios/meson-build:latest
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run: 
          name: Build
          command: meson build -Db_coverage=true
      - run: 
          name: Run tests
          command: ninja -C build test coverage-xml

workflows:
  mqtt-system-monitor-workflow:
    jobs:
      - build:
          post-steps:
            - codecov/upload:
                file: build/meson-logs/coverage.xml
