version: 2.1

jobs:
  build:
    docker:
      - image: nychtelios/meson-build:latest 
    steps:
      - checkout
      - run: 
          name: Build
          command: meson build
      - run: 
          name: Run tests
          command: ninja -C build test

workflows:
  mqtt-system-monitor-workflow:
    jobs:
      - build
