version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: nychtelios/meson-build:latest
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run: 
          name: Build
          command: meson build -Db_coverage=true
      - run: 
          name: Run tests
          command: ninja -C build test coverage-xml
      - coveralls/upload:
          path_to_lcov: build/meson-logs/coverage.xml

workflows:
  mqtt-system-monitor-workflow:
    jobs:
      - build
